import subprocess
from git import Repo
from datetime import datetime


def clone_repo(repo_url, target_dir):
    """
    Clone a git repository to target directory.
    Returns (repo_path, success, error_msg)
    """
    try:
        print(f"🔄 Cloning {repo_url}...")
        repo = Repo.clone_from(repo_url, target_dir)
        print(f"✅ Cloned to {target_dir}")
        return target_dir, True, None
    except Exception as e:
        return None, False, str(e)


def create_branch(repo_path, branch_name):
    """
    Create and checkout a new branch.
    Returns (success, error_msg)
    """
    try:
        repo = Repo(repo_path)
        
        # Create new branch from current HEAD
        new_branch = repo.create_head(branch_name)
        new_branch.checkout()
        
        print(f"✅ Created and switched to branch: {branch_name}")
        return True, None
    except Exception as e:
        return False, str(e)


def commit_changes(repo_path, message):
    """
    Stage all changes and commit.
    Returns (success, error_msg)
    """
    try:
        repo = Repo(repo_path)
        
        # Check if there are changes
        if not repo.is_dirty() and not repo.untracked_files:
            return False, "No changes to commit"
        
        # Stage all changes
        repo.git.add(A=True)
        
        # Commit
        repo.index.commit(message)
        
        print(f"✅ Committed: {message}")
        return True, None
    except Exception as e:
        return False, str(e)


def push_branch(repo_path, branch_name):
    """
    Push branch to remote origin.
    Returns (success, error_msg)
    """
    try:
        repo = Repo(repo_path)
        
        # Push to origin
        origin = repo.remote(name='origin')
        origin.push(branch_name)
        
        print(f"✅ Pushed branch: {branch_name}")
        return True, None
    except Exception as e:
        return False, str(e)


def create_pull_request(repo_url, branch_name, title, body):
    """
    Create a pull request using GitHub CLI (gh).
    Requires: gh CLI installed and authenticated.
    Returns (pr_url, success, error_msg)
    """
    try:
        # Extract owner/repo from URL
        # Example: https://github.com/owner/repo.git -> owner/repo
        if repo_url.endswith('.git'):
            repo_url = repo_url[:-4]
        
        parts = repo_url.rstrip('/').split('/')
        repo_name = f"{parts[-2]}/{parts[-1]}"
        
        # Create PR using gh CLI
        cmd = [
            'gh', 'pr', 'create',
            '--repo', repo_name,
            '--head', branch_name,
            '--title', title,
            '--body', body
        ]
        
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True
        )
        
        pr_url = result.stdout.strip()
        print(f"✅ Created PR: {pr_url}")
        return pr_url, True, None
        
    except subprocess.CalledProcessError as e:
        error_msg = e.stderr if e.stderr else str(e)
        return None, False, f"GitHub CLI error: {error_msg}"
    except Exception as e:
        return None, False, str(e)


def get_repo_info(repo_path):
    """
    Get repository information.
    Returns dict with branch, remote, etc.
    """
    try:
        repo = Repo(repo_path)
        
        info = {
            'current_branch': repo.active_branch.name,
            'is_dirty': repo.is_dirty(),
            'untracked_files': len(repo.untracked_files),
            'remotes': [remote.name for remote in repo.remotes],
        }
        
        if repo.remotes:
            info['remote_url'] = repo.remotes.origin.url
        
        return info
    except Exception as e:
        return {'error': str(e)}


def generate_branch_name(prefix="fix"):
    """
    Generate a unique branch name.
    """
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    return f"{prefix}/auto-fixes-{timestamp}"


def generate_pr_body(fixed_count, issues_fixed):
    """
    Generate PR description body.
    """
    body = f"""## 🤖 Automated Code Fixes

This PR was automatically generated by AGI Engineer Bot.

### Summary
- **Fixed Issues**: {fixed_count}
- **Tool**: Ruff static analyzer

### Changes
"""
    
    # Group by rule code
    from collections import Counter
    rule_counts = Counter(issue['code'] for issue in issues_fixed)
    
    for rule_code, count in rule_counts.most_common():
        body += f"- `{rule_code}`: {count} fixes\n"
    
    body += """
### Rule Descriptions
- **F401**: Removed unused imports
- **F541**: Removed unnecessary f-string prefixes
- **W291**: Removed trailing whitespace
- **W292**: Added newline at end of file

All changes have been automatically verified and should not break existing functionality.

---
*Generated by AGI Engineer Bot 🤖*
"""
    
    return body
